docker compose exec -T db sh -lc '
  PGPASSWORD="$POSTGRES_PASSWORD" \
  psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -p "${PGPORT:-5432}" \
  -v TARGET_SRID="$TARGET_SRID" \
  -v ADMIN_BUFFER="$ADMIN_BUFFER" \
  -v DEFAULT_POINT_IF_SMALL_AREA="$DEFAULT_POINT_IF_SMALL_AREA" \
  -v ON_ERROR_STOP=1 \
  -f /sql/main.sql
'